### PR TITLE
Small fix on toolpalette

### PR DESCRIPTION
**Pull request by comedinha**

### CODE REVIEW

**Comment by asamy** [comment]
See my comment https://github.com/allanference/forgottenmapeditor/commit/b539c98ba923e763f0953f8d87a7c9cffa2753c6#commitcomment-3885987

**Comment by comedinha** [comment]
yes, most leave here if he claims ... The item and returned in 'number'

**Comment by asamy** [comment]
I don't really get what you've just said...

Anyways, just return if it's a string so:

``` lua
if type(_G["currentThing"]) == 'string' or type(_G["secondThing"]) == 'string' then
  return
end
```

I'd say wait to see @Crypton33 's comment on this since it's his code.

**Comment by comedinha** [comment]
ok.

**Comment by asamy** [comment]
Fixed in https://github.com/allanference/forgottenmapeditor/commit/cb77b5e3425b266572dbb2a45cb9581dbe7c420d

**Pull request closed without merging**
